import express from "express";
import { academicPrograms } from "./config/academicPrograms.js";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import compression from "compression";
import rosterRoutes from "./routes/rosterRoutes.js";
import adminRoutes from "./routes/adminRoutes.js";
import authRoutes from "./routes/authRoutes.js";
import companyRoutes from "./routes/companyRoutes.js";
import applicationRoutes from "./routes/applicationRoutes.js";
import uploadRoutes from "./routes/upload.routes.js";
import studentExperienceRoutes from "./routes/studentExperienceRoutes.js";
import rateLimiter from "./middleware/rateLimiter.js";
import csrfProtection from "./middleware/csrfMiddleware.js";
import errorMiddleware from "./middleware/errorMiddleware.js";
import { corsOptions } from "./config/cors.js";
import { protect } from "./middleware/authMiddleware.js";
import { serializeUser } from "./services/authService.js";

export function createApp({ rateLimit = true } = {}) {
  const app = express();
  app.set("trust proxy", 1);
  app.use(helmet(), compression(), cors(corsOptions()), cookieParser());
  app.use(csrfProtection);
  app.use("/api/admin/roster/imports", express.json({ limit: "2mb" }));
  app.use("/api/company", express.json({ limit: "1mb" }));
  app.use(express.json({ limit: "100kb" }), express.urlencoded({ extended: false, limit: "100kb" }));
  if (rateLimit) app.use(rateLimiter);
  app.get("/health", (req, res) => res.json({ success: true, message: "Server is healthy" }));
  app.get("/", (req, res) => res.send("API is running..."));
  app.get("/api/academics", (req, res) => res.json({ programs: academicPrograms }));
  app.use("/api/auth", authRoutes);
  app.use("/api/admin/roster", rosterRoutes);
  app.use("/api/admin/accounts", adminRoutes);
  app.use("/api/company", companyRoutes);
  app.use("/api/application", applicationRoutes);
  app.use("/api/student", studentExperienceRoutes);
  app.use("/api/v1/upload", uploadRoutes);
  app.get("/api/protected", protect, (req, res) => res.json({ success: true, user: serializeUser(req.user) }));
  app.use((req, res) => res.status(404).json({ success: false, message: "Route not found" }));
  app.use(errorMiddleware);
  return app;
}
