import { useState } from "react";
import API from "../api/axios.js";
import { formatPortalDate } from "../utils/studentExperience.js";
export default function ApplicationSnapshot({ snapshot = {}, canViewResume = true, studentId, compact = false }) {
  const [error, setError] = useState("");
  const fields = [["Name", snapshot.name], ["Email", snapshot.email], ["Roll number", snapshot.enrollmentNo], ["Course / branch", [snapshot.course, snapshot.branch].filter(Boolean).join(" / ")], ["Graduating year", snapshot.passingYear], ["Phone", snapshot.contactNo], ["CGPA", snapshot.cgpa], ["Active / total backlogs", snapshot.activeBacklogs == null ? null : `${snapshot.activeBacklogs} / ${snapshot.totalBacklogs ?? '—'}`], ["10th marks", snapshot.tenthPercentage == null ? null : `${snapshot.tenthPercentage}%`], [snapshot.entryQualification === "DIPLOMA" ? "Diploma marks" : "12th marks", (snapshot.entryQualification === "DIPLOMA" ? snapshot.diplomaPercentage : snapshot.twelfthPercentage) == null ? null : `${snapshot.entryQualification === "DIPLOMA" ? snapshot.diplomaPercentage : snapshot.twelfthPercentage}%`]];
  async function openResume() { try { const { data } = await API.get(`/v1/upload/resume/view${studentId ? `/${studentId}` : ''}`, { params: { versionId: snapshot.resume.versionId } }); window.open(data.signedUrl, "_blank", "noopener,noreferrer"); } catch { setError("Unable to open this resume version. Please try again."); } }
  return <div className="space-y-4"><dl className={`grid gap-3 text-sm sm:grid-cols-2 ${compact ? "grid-cols-2 xl:grid-cols-3" : ""}`}>{fields.map(([label, value]) => <div key={label} className="min-w-0"><dt className={compact ? "text-xs text-slate-400" : "text-slate-400"}>{label}</dt><dd className="mt-1 break-words">{value ?? "Not provided"}</dd></div>)}</dl>
    <details className="text-sm"><summary className="cursor-pointer text-cyan-300">Additional submitted details</summary><dl className={`mt-3 grid gap-3 sm:grid-cols-2 ${compact ? "grid-cols-2 xl:grid-cols-3" : ""}`}>{[["College", snapshot.collegeName], ["Semester", snapshot.semester], ["WhatsApp", snapshot.whatsappNo], ["Counselor group", snapshot.counselorGroup], ["Skills", snapshot.skills?.join(", ")], ["GitHub", snapshot.githubUrl], ["LinkedIn", snapshot.linkedinUrl], ...(snapshot.entryQualification === "DIPLOMA" ? [["Diploma branch", snapshot.diplomaBranch], ["Diploma college", snapshot.diplomaCollege], ["Diploma passing year", snapshot.diplomaPassingYear]] : [["12th stream", snapshot.twelfthStream]])].map(([label, value]) => <div key={label} className="min-w-0"><dt className={compact ? "text-xs text-slate-400" : "text-slate-400"}>{label}</dt><dd className="mt-1 break-words">{value || "Not provided"}</dd></div>)}</dl>{snapshot.semesterCgpa?.length > 0 && <p className="mt-3">Semester CGPA: {snapshot.semesterCgpa.map(item => `Sem ${item.sem}: ${item.cgpa}`).join(" · ")}</p>}{snapshot.projects?.length > 0 && <div className="mt-3 space-y-3"><h4 className="font-semibold">Projects</h4>{snapshot.projects.map((project, index) => <div key={index} className="break-words"><p>{project.title}</p><p className="whitespace-pre-wrap text-slate-400">{project.description}</p><p className="text-slate-400">{project.projectUrl}</p></div>)}</div>}</details>
    {snapshot.portfolioLinks?.length > 0 && <div className="text-sm"><h4 className="font-semibold">Portfolio links</h4><dl className={`mt-3 grid gap-3 sm:grid-cols-2 ${compact ? "grid-cols-2 xl:grid-cols-3" : ""}`}>{snapshot.portfolioLinks.map((link, index) => <div key={index} className="min-w-0"><dt className={compact ? "text-xs text-slate-400" : "text-slate-400"}>{link.label}</dt><dd className="mt-1 break-words">{/^https?:\/\//.test(link.url) ? <a href={link.url} target="_blank" rel="noopener noreferrer" className="text-cyan-300 hover:underline">{link.url}</a> : link.url}</dd></div>)}</dl></div>}
    {snapshot.resume?.versionId ? <div className="rounded-xl border border-white/10 p-3 text-sm"><p className="break-words">Resume: {snapshot.resume.fileName || "Uploaded resume"}</p><p className="mt-1 text-xs text-slate-400">Uploaded {formatPortalDate(snapshot.resume.uploadedAt)}</p>{canViewResume && <button type="button" className="mt-2 text-cyan-300 underline" onClick={openResume}>View this resume version</button>}</div> : <p className="text-sm text-slate-400">No resume version recorded.</p>}
    {error && <p role="alert" className="text-sm text-red-300">{error}</p>}
  </div>;
}
